spring:
  application:
    name: lodeur
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
server:
  port: 8088
  address: 127.0.0.1
  servlet:
    context-path: /
logging:
  config: classpath:log4j2.properties